export const availabilitySlots = {
  FETCH_AVAILABILITY_LOADING: 'FETCH_AVAILABILITY_LOADING',
  FETCH_AVAILABILITY_SUCCESS: 'FETCH_AVAILABILITY_SUCCESS',
  FETCH_AVAILABILITY_FAILURE: 'FETCH_AVAILABILITY_FAILURE',
};
