export const customer_service = {
  VERIFY_BOOKING_CODE_LOADING: 'VERIFY_BOOKING_CODE_LOADING',
  VERIFY_BOOKING_CODE_SUCCESS: 'VERIFY_BOOKING_CODE_SUCCESS',

  UPDATE_STATUS_SUCCESS: 'UPDATE_STATUS_SUCCESS',

  FETCH_FLOW_BOARD_LOADING: 'FETCH_FLOW_BOARD_LOADING',
  FETCH_FLOW_BOARD_SUCCESS: 'FETCH_FLOW_BOARD_SUCCESS',

  FETCH_SERVICES_OPTIONS_BY_BUSINESS_ADMIN_ID_LOADING: 'FETCH_SERVICES_OPTIONS_BY_BUSINESS_ADMIN_ID_LOADING',
  FETCH_SERVICES_OPTIONS_BY_BUSINESS_ADMIN_ID_SUCCESS: 'FETCH_SERVICES_OPTIONS_BY_BUSINESS_ADMIN_ID_SUCCESS',

  FETCH_PROVIDERS_OPTIONS_BY_BUSINESS_ADMIN_ID_LOADING: 'FETCH_PROVIDERS_OPTIONS_BY_BUSINESS_ADMIN_ID_LOADING',
  FETCH_PROVIDERS_OPTIONS_BY_BUSINESS_ADMIN_ID_SUCCESS: 'FETCH_PROVIDERS_OPTIONS_BY_BUSINESS_ADMIN_ID_SUCCESS',
};
