export const event   = {
    FETCH_EVENTS_LOADING : 'FETCH_EVENTS_LOADING',
    FETCH_EVENTS_SUCCESS : 'FETCH_EVENTS_SUCCESS',
    FETCH_EVENTS_FAILURE : 'FETCH_EVENTS_FAILURE',

    CREATE_EVENT_LOADING : 'CREATE_EVENT_LOADING',
    CREATE_EVENT_SUCCESS : 'CREATE_EVENT_SUCCESS',
    CREATE_EVENT_FAILURE : 'CREATE_EVENT_FAILURE',

    EDIT_EVENT_LOADING :   'EDIT_EVENT_LOADING',
    EDIT_EVENT_SUCCESS :   'EDIT_EVENT_SUCCESS',
    EDIT_EVENT_FAILURE :   'EDIT_EVENT_FAILURE',


    FETCH_EVENT_LOADING : 'FETCH_EVENT_LOADING',
    FETCH_EVENT_SUCCESS : 'FETCH_EVENT_SUCCESS',
    FETCH_EVENT_FAILURE : 'FETCH_EVENT_FAILURE',

}
