export const location = {
    FETCH_ALL_LOCATIONS_LOADING: 'FETCH_ALL_LOCATIONS_LOADING',
    FETCH_ALL_LOCATIONS_SUCCESS: 'FETCH_ALL_LOCATIONS_SUCCESS',
    FETCH_ALL_LOCATIONS_FAILURE: 'FETCH_ALL_LOCATIONS_FAILURE'
}