export const organization = {
    FETCH_BUSINESS : 'FETCH_BUSINESS',
    FETCH_BUSINESS_SUCCESS : 'FETCH_BUSINESS_SUCCESS',
    FETCH_BUSINESS_FAILURE : 'FETCH_BUSINESS_FAILURE',

    CREATE_ORGANIZATION_LOADING : 'CREATE_ORGANIZATION_LOADING',
    CREATE_ORGANIZATION_SUCCESS : 'CREATE_ORGANIZATION_SUCCESS',
    CREATE_ORGANIZATION_FAILURE : 'CREATE_ORGANIZATION_FAILURE',

    ORGANIZATION_BY_ADMIN_LOADING: 'ORGANIZATION_BY_ADMIN_LOADING',
    ORGANIZATION_BY_ADMIN_SUCCESS: 'ORGANIZATION_BY_ADMIN_SUCCESS',
    ORGANIZATION_BY_ADMIN_FAILURE: 'ORGANIZATION_BY_ADMIN_FAILURE',

    EDIT_ORGANIZATION_LOADING: 'EDIT_ORGANIZATION_LOADING',
    EDIT_ORGANIZATION_SUCCESS: 'EDIT_ORGANIZATION_SUCCESS',
    EDIT_ORGANIZATION_FAILURE: 'EDIT_ORGANIZATION_FAILURE',

    FETCH_ORGANIZATION_LOADING: 'FETCH_ORGANIZATION_LOADING',
    FETCH_ORGANIZATION_SUCCESS: 'FETCH_ORGANIZATION_SUCCESS',
    FETCH_ORGANIZATION_FAILURE: 'FETCH_ORGANIZATION_FAILURE'

}
