export const organization = {
    FETCH_BUSINESS : 'FETCH_BUSINESS',
    FETCH_BUSINESS_SUCCESS : 'FETCH_BUSINESS_SUCCESS',
    FETCH_BUSINESS_FAILURE : 'FETCH_BUSINESS_FAILURE',

    CREATE_ORGANIZATION_LOADING : 'CREATE_ORGANIZATION_LOADING',
    CREATE_ORGANIZATION_SUCCESS : 'CREATE_ORGANIZATION_SUCCESS',
    CREATE_ORGANIZATION_FAILURE : 'CREATE_ORGANIZATION_FAILURE'

}