export const provider = {
    FETCH_PROVIDERS : 'FETCH_PROVIDERS',
    FETCH_PROVIDERS_SUCCESS : 'FETCH_PROVIDERS_SUCCESS',
    FETCH_PROVIDERS_FAILURE : 'FETCH_PROVIDERS_FAILURE',

    CREATE_PROVIDER_LOADING : 'CREATE_PROVIDER_LOADING',
    CREATE_PROVIDER_SUCCESS : 'CREATE_PROVIDER_SUCCESS',
    CREATE_PROVIDER_FAILURE : 'CREATE_PROVIDER_FAILURE',

    EDIT_PROVIDER_LOADING : 'EDIT_PROVIDER_LOADING',
    EDIT_PROVIDER_SUCCESS : 'EDIT_PROVIDER_SUCCESS',
    EDIT_PROVIDER_FAILURE : 'EDIT_PROVIDER_FAILURE',


    FETCH_PROVIDER : 'FETCH_PROVIDER',
    FETCH_PROVIDER_SUCCESS : 'FETCH_PROVIDER_SUCCESS',
    FETCH_PROVIDER_FAILURE : 'FETCH_PROVIDER_FAILURE',

    FETCH_TIMEZONES_LOADING: 'FETCH_TIMEZONES_LOADING',
    FETCH_TIMEZONES_SUCCESS: 'FETCH_TIMEZONES_SUCCESS',
    FETCH_TIMEZONES_FAILURE: 'FETCH_TIMEZONES_FAILURE'

}
