export const service = {
    FETCH_SERVICE_LOADING: 'FETCH_SERVICE_LOADING',
    FETCH_SERVICE_SUCCESS :'FETCH_SERVICE_SUCCESS',
    FETCH_SERVICE_FAILURE: 'FETCH_SERVICE_FAILURE',

    FETCH_SERVICES_LOADING: 'FETCH_SERVICES_LOADING',
    FETCH_SERVICES_SUCCESS :'FETCH_SERVICES_SUCCESS',
    FETCH_SERVICES_FAILURE: 'FETCH_SERVICES_FAILURE',

    CREATE_SERVICE_LOADING: 'CREATE_SERVICE_LOADING',
    CREATE_SERVICE_SUCCESS: 'CREATE_SERVICE_SUCCESS',
    CREATE_SERVICE_FAILURE: 'CREATE_SERVICE_FAILURE',

    FETCH_CATEGORY_LOADING: 'FETCH_CATEGORY_LOADING',
    FETCH_CATEGORY_SUCCESS: 'FETCH_CATEGORY_SUCCESS',
    FETCH_CATEGORY_FAILURE: 'FETCH_CATEGORY_FAILURE',

    EDIT_SERVICE_LOADING: 'EDIT_SERVICE_LOADING',
    EDIT_SERVICE_SUCCESS: 'EDIT_SERVICE_SUCCESS',
    EDIT_SERVICE_FAILURE: 'EDIT_SERVICE_FAILURE'
}
