export const service = {
    FETCH_SERVICES: 'FETCH_SERVICES',
    FETCH_SERVICES_SUCCESS :'FETCH_SERVICES_SUCCESS',
    FETCH_SERVICES_FAILURE: 'FETCH_SERVICES_FAILURE',

    CREATE_SERVICE: 'CREATE_SERVICE',
    CREATE_SERVICE_SUCCESS: 'CREATE_SERVICE_SUCCESS',
    CREATE_SERVICE_FAILURE: 'CREATE_SERVICE_FAILURE',

    FETCH_CATEGORY: 'FETCH_CATEGORY',
    FETCH_CATEGORY_SUCCESS: 'FETCH_CATEGORY_SUCCESS',
    FETCH_CATEGORY_FAILURE: 'FETCH_CATEGORY_FAILURE',

    FETCH_SERVICE_BY_ID: 'FETCH_SERVICE_BY_ID',
    FETCH_SERVICE_BY_ID_SUCCESS: 'FETCH_SERVICE_BY_ID_SUCCESS',
    FETCH_SERVICE_BY_ID_FAILURE: 'FETCH_SERVICE_BY_ID_FAILURE',

    EDIT_SERVICE: 'EDIT_SERVICE',
    EDIT_SERVICE_SUCCESS: 'EDIT_SERVICE_SUCCESS',
    EDIT_SERVICE_FAILURE: 'EDIT_SERVICE_FAILURE'
}
