export const serviceProvider = {
  FETCH_SERVICE_PROVIDERS_LOADING: 'FETCH_SERVICE_PROVIDERS_LOADING',
  FETCH_SERVICE_PROVIDERS_SUCCESS: 'FETCH_SERVICE_PROVIDERS_SUCCESS',
  FETCH_SERVICE_PROVIDERS_FAILURE: 'FETCH_SERVICE_PROVIDERS_FAILURE',

  CREATE_SERVICE_PROVIDER_LOADING: 'CREATE_SERVICE_PROVIDER_LOADING',
  CREATE_SERVICE_PROVIDER_SUCCESS: 'CREATE_SERVICE_PROVIDER_SUCCESS',
  CREATE_SERVICE_PROVIDER_FAILURE: 'CREATE_SERVICE_PROVIDER_FAILURE',

  EDIT_SERVICE_PROVIDER_LOADING: 'EDIT_SERVICE_PROVIDER_LOADING',
  EDIT_SERVICE_PROVIDER_SUCCESS: 'EDIT_SERVICE_PROVIDER_SUCCESS',
  EDIT_SERVICE_PROVIDER_FAILURE: 'EDIT_SERVICE_PROVIDER_FAILURE',

  FETCH_SERVICE_CATEGORIES_LOADING: 'FETCH_SERVICE_CATEGORIES_LOADING',
  FETCH_SERVICE_CATEGORIES_SUCCESS: 'FETCH_SERVICE_CATEGORIES_SUCCESS',
  FETCH_SERVICE_CATEGORIES_FAILURE: 'FETCH_SERVICE_CATEGORIES_FAILURE',

  FETCH_SERVICE_PROVIDER_LOADING: 'FETCH_SERVICE_PROVIDER_LOADING',
  FETCH_SERVICE_PROVIDER_SUCCESS: 'FETCH_SERVICE_PROVIDER_SUCCESS',
  FETCH_SERVICE_PROVIDER_FAILURE: 'FETCH_SERVICE_PROVIDER_FAILURE'
};
