export const serviceProvider = {
    FETCH_SERVICE_PROVIDERS : 'FETCH_SERVICE_PROVIDERS',
    FETCH_SERVICE_PROVIDERS_SUCCESS : 'FETCH_SERVICE_PROVIDERS_SUCCESS',
    FETCH_SERVICE_PROVIDERS_FAILURE : 'FETCH_SERVICE_PROVIDERS_FAILURE',

    UPDATE_SERVICE_PROVIDER: 'UPDATE_SERVICE_PROVIDER',
    UPDATE_SERVICE_PROVIDER_LOADING : 'UPDATE_SERVICE_PROVIDER_LOADING',
    UPDATE_SERVICE_PROVIDER_SUCCESS : 'UPDATE_SERVICE_PROVIDER_SUCCESS',
    UPDATE_SERVICE_PROVIDER_FAILURE : 'UPDATE_SERVICE_PROVIDER_FAILURE',

    FETCH_SERVICE_PROVIDER : 'FETCH_SERVICE_PROVIDER',
    FETCH_SERVICE_PROVIDER_SUCCESS : 'FETCH_SERVICE_PROVIDER_SUCCESS',
    FETCH_SERVICE_PROVIDER_FAILURE : 'FETCH_SERVICE_PROVIDER_FAILURE',

}
