export const special_event = {

  LOADING: 'FETCH_SPECIAL_EVENTS_LOADING',
  SUCCESS: 'FETCH_SPECIAL_EVENTS_SUCCESS',

  DEL_SPECIAL_EVENT_LOADING: 'DEL_SPECIAL_EVENT_LOADING',
  DEL_SPECIAL_EVENT_SUCCESS: 'DEL_SPECIAL_EVENT_SUCCESS',
  DEL_SPECIAL_EVENT_FAILURE: 'DEL_SPECIAL_EVENT_FAILURE',

};
