export const specialEventDetail = {
  FETCH_SPECIAL_EVENT_DETAIL_LOADING: 'FETCH_SPECIAL_EVENT_DETAIL_LOADING',
  FETCH_SPECIAL_EVENT_DETAIL_SUCCESS: 'FETCH_SPECIAL_EVENT_DETAIL_SUCCESS',
  FETCH_SPECIAL_EVENT_DETAIL_FAILURE: 'FETCH_SPECIAL_EVENT_DETAIL_FAILURE',
};
