export const tmp_service = {

  FETCH_TMP_SERVICES_LOADING: 'FETCH_TMP_SERVICES_LOADING',
  FETCH_TMP_SERVICES_SUCCESS: 'FETCH_TMP_SERVICES_SUCCESS',

  DEL_TMP_SERVICE_LOADING: 'DEL_TMP_SERVICE_LOADING',
  DEL_TMP_SERVICE_SUCCESS: 'DEL_TMP_SERVICE_SUCCESS',
  TMP_SERVICE_FAILURE: 'TMP_SERVICE_FAILURE',

  SET_TMP_SERVICE: 'SET_TMP_SERVICE',
};
